from django.urls import path
from app_principal import views

urlpatterns = [    
    path('', views.Home.as_view(), name='Home'),
    path('listarUsuarios/', views.ListarUsuarios.as_view(), name='ListarUsuarios'),
    path('listarAliados/', views.ListarAliados.as_view(), name='ListarAliados'),
    path('listarCompaneros/', views.ListarCompaneros.as_view(), name='ListarCompaneros'),
    path('listarEnemigos/', views.ListarEnemigos.as_view(), name='ListarEnemigos'),
    path('listarHechos/', views.ListarHechos.as_view(), name='ListarHechos'),
    path('listarPersonas/', views.ListarPersonas.as_view(), name='ListarPersonas'),
    path('listarMisiones/', views.ListarMisiones.as_view(), name='ListarMisiones'),
    path('listarContratos/', views.ListarContratos.as_view(), name='ListarContratos'),
    path('crearUsuarios/', views.CrearUsuarios.as_view(), name='CrearUsuarios'),
    path('crearAliados/', views.CrearAliados.as_view(), name='CrearAliados'),   
    path('crearCompaneros/',views.CrearCompaneros.as_view(), name='CrearCompaneros'),
    path('crearEnemigos/',views.CrearEnemigos.as_view(), name='CrearEnemigos'),
    path('crearHechos/',views.CrearHechos.as_view(), name='CrearHechos'),
    path('crearSalvados/',views.CrearSalvados.as_view(), name='CrearSalvados'),
    path('crearMisiones/',views.CrearMisiones.as_view(), name='CrearMisiones'),
    path('crearContratos/',views.CrearContratos.as_view(), name='CrearContratos'), 
    path('editarUsuarios/edit<int:pk>',views.EditarUsuarios.as_view(), name='EditarUsuarios'),
    path('editarAliados/edit<str:pk>',views.EditarAliados.as_view(), name='EditarAliados'),
    path('editarCompaneros/edit<str:pk>',views.EditarCompaneros.as_view(), name='EditarCompaneros'),
    path('editarEnemigos/edit<str:pk>',views.EditarEnemigos.as_view(), name='EditarEnemigos'),
    path('editarHechos/edit<int:pk>',views.EditarHechos.as_view(), name='EditarHechos'),
    path('editarPersonas/edit<int:pk>',views.EditarPersonas.as_view(), name='EditarPersonas'),
    path('editarMisiones/edit<str:pk>',views.EditarMisiones.as_view(), name='EditarMisiones'),
    path('editarContratos/edit<int:pk>',views.EditarContratos.as_view(), name='EditarContratos'),
    path('eliminarUsuarios/<int:pk>',views.EliminarUsuarios.as_view(), name='EliminarUsuarios'),
    path('eliminarAliados/<str:pk>',views.EliminarAliados.as_view(), name='EliminarAliados'),
    path('eliminarCompaneros/<str:pk>',views.EliminarCompaneros.as_view(), name='EliminarCompaneros'),
    path('eliminarEnemigos/<str:pk>',views.EliminarEnemigos.as_view(), name='EliminarEnemigos'),    
    path('eliminarPersonas/<int:pk>',views.EliminarPersonas.as_view(), name='EliminarPersonas'),
    path('eliminarMisiones/<str:pk>',views.EliminarMisiones.as_view(), name='EliminarMisiones'),
    path('eliminarContratos/<int:pk>',views.EliminarContratos.as_view(), name='EliminarContratos'),
    path('eliminarHechos/<int:pk>',views.EliminarHechos.as_view(), name='EliminarHechos'),
]
