# Generated by Django 3.1 on 2020-09-01 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliado',
            name='es_extraterrestre_aliado',
            field=models.BooleanField(verbose_name='Extraterrestre'),
        ),
        migrations.AlterField(
            model_name='aliado',
            name='idioma_aliado',
            field=models.CharField(max_length=20, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='aliado',
            name='nombre_aliado',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='aliado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.usuario', verbose_name='Aliado de'),
        ),
        migrations.AlterField(
            model_name='companero_equipo',
            name='cumpleanos_companero',
            field=models.DateField(blank=True, verbose_name='Cumpleaños'),
        ),
        migrations.AlterField(
            model_name='companero_equipo',
            name='email_companero',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='companero_equipo',
            name='nombre_companero',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='companero_equipo',
            name='telefono_companero',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='companero_equipo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.usuario', verbose_name='Compañero de'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fin_contrato',
            field=models.DateField(verbose_name='Fin contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='ganancia_por_contrato',
            field=models.FloatField(verbose_name='Ganancia por contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='inicio_contrato',
            field=models.DateField(verbose_name='Inicio contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nombre_patrocinador',
            field=models.CharField(max_length=30, verbose_name='Patrocinador'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='ref_contrato',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.usuario', verbose_name='Contrato de'),
        ),
        migrations.AlterField(
            model_name='enemigo',
            name='alias_enemigo',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='enemigo',
            name='es_extraterrestre_enemigo',
            field=models.BooleanField(verbose_name='Extraterrestre'),
        ),
        migrations.AlterField(
            model_name='enemigo',
            name='habilidad_principal_enemigo',
            field=models.CharField(max_length=20, verbose_name='Habilidad ppal'),
        ),
        migrations.AlterField(
            model_name='enemigo',
            name='nombre_real_enemigo',
            field=models.CharField(max_length=30, verbose_name='Nombre real'),
        ),
        migrations.AlterField(
            model_name='enemigo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.usuario', verbose_name='Enemigo de'),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='descripcion_hecho',
            field=models.TextField(blank=True, max_length=400, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='fecha_hecho',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='lugar_hecho',
            field=models.CharField(max_length=20, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.persona_salvada', verbose_name='Salvado'),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.usuario', verbose_name='Salvador'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='codigo',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Código misión'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='fecha',
            field=models.DateTimeField(unique=True, verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='nombre_mision',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='usuario',
            field=models.ForeignKey(default='Steve Rogers', on_delete=django.db.models.deletion.CASCADE, to='app_principal.usuario', verbose_name='Misión de'),
        ),
        migrations.AlterField(
            model_name='persona_salvada',
            name='edad_persona_salvada',
            field=models.IntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='persona_salvada',
            name='id_persona',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID persona'),
        ),
        migrations.AlterField(
            model_name='persona_salvada',
            name='nombre_persona_salvada',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos_usuario',
            field=models.CharField(max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni_usuario',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres_usuario',
            field=models.CharField(max_length=30, verbose_name='Nombres'),
        ),
    ]
