# Generated by Django 3.1 on 2020-09-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0002_auto_20200901_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='mision',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'pendiente'), ('CUMPLIDA', 'cumplida'), ('FALLIDA', 'fallida')], default='PENDIENTE', max_length=9),
        ),
    ]
