# Generated by Django 3.1 on 2020-09-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0003_mision_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mision',
            name='cumplida',
        ),
        migrations.RemoveField(
            model_name='mision',
            name='fallida',
        ),
        migrations.RemoveField(
            model_name='mision',
            name='pendiente',
        ),
        migrations.AlterField(
            model_name='mision',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CUMPLIDA', 'Cumplida'), ('FALLIDA', 'Fallida')], default='PENDIENTE', max_length=9),
        ),
    ]
