# Generated by Django 3.1 on 2020-09-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0004_auto_20200901_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliado',
            name='idioma_aliado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.persona_salvada', verbose_name='Salvó a'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='codigo',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.usuario', verbose_name='Misión de'),
        ),
        migrations.AlterUniqueTogether(
            name='mision',
            unique_together={('usuario', 'fecha')},
        ),
    ]
