# Generated by Django 3.1 on 2020-09-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0005_auto_20200901_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companero_equipo',
            name='cumpleanos_companero',
            field=models.DateField(blank=True, null=True, verbose_name='Cumpleaños'),
        ),
    ]
