# Generated by Django 3.1 on 2020-09-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0007_auto_20200901_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mision',
            name='observaciones',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
