# Generated by Django 3.1 on 2020-09-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0008_auto_20200901_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='ref_contrato',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.usuario', verbose_name='Misión para'),
        ),
        migrations.AlterField(
            model_name='persona_salvada',
            name='edad_persona_salvada',
            field=models.PositiveIntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni_usuario',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='DNI'),
        ),
    ]
