# Generated by Django 3.1 on 2020-09-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0009_auto_20200901_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona_salvada',
            name='id_persona',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID persona'),
        ),
    ]
